#!/bin/bash

# ==============================================================================
# AUTOMATICALLY GENERATED ANDROID CLI BUILD PIPELINE
# Generated by LinGenerateSH
# Project: Minimalist eBook Engine
# Android Platform: API 36
# Build Tools: 36.0.0
# Minimum SDK: 29
# Target SDK: 36
# Java compatibility: 1.8
# Runtime compiler: OpenJDK 21
# DEX compiler: D8 36.0.0
# APK signing: APK Signature Scheme V2 + V3
# ==============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

export ANDROID_HOME=/usr/java/android
export JAVA_HOME=/usr/java/jdk-21.0.2

export BUILD_TOOLS=$ANDROID_HOME/build-tools/36.0.0
export ANDROID_JAR=$ANDROID_HOME/platforms/android-36/android.jar
export D8_JAR=$BUILD_TOOLS/lib/d8.jar

export AAPT=$BUILD_TOOLS/aapt
export ZIPALIGN=$BUILD_TOOLS/zipalign
export APKSIGNER=$BUILD_TOOLS/apksigner

export PATH=$JAVA_HOME/bin:$BUILD_TOOLS:$ANDROID_HOME/platform-tools:$PATH

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

check_error() {
    if [ $? -ne 0 ]; then
        echo -e "${RED}[ERROR] Critical failure encountered during: $1${NC}"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# STEP 1: ENVIRONMENT CHECK
# ------------------------------------------------------------------------------
log_info "Checking Java and Android build environment..."

java -version

if [ ! -f "$ANDROID_JAR" ]; then
    echo -e "${RED}[ERROR] android-36/android.jar not found:${NC}"
    echo "$ANDROID_JAR"
    exit 1
fi

if [ ! -f "$D8_JAR" ]; then
    echo -e "${RED}[ERROR] D8 JAR not found:${NC}"
    echo "$D8_JAR"
    exit 1
fi

if [ ! -x "$AAPT" ]; then
    echo -e "${RED}[ERROR] AAPT 36.0.0 not found:${NC}"
    echo "$AAPT"
    exit 1
fi

if [ ! -x "$ZIPALIGN" ]; then
    echo -e "${RED}[ERROR] ZIPALIGN 36.0.0 not found:${NC}"
    echo "$ZIPALIGN"
    exit 1
fi

if [ ! -x "$APKSIGNER" ]; then
    echo -e "${RED}[ERROR] APKSIGNER 36.0.0 not found:${NC}"
    echo "$APKSIGNER"
    exit 1
fi

log_success "Android API 36 build environment found."

# ------------------------------------------------------------------------------
# STEP 2: INITIAL CLEANUP
# ------------------------------------------------------------------------------
log_info "Removing previous generated APK and build artifacts..."

rm -fv ../*.keystore.old
rm -fv ../classes.dex
rm -fv ../bin/*.apk
rm -fv ../bin/*.idsig
rm -fv ../bin/*.signed.*
rm -fv ../bin/*.unsigned.*
rm -fv ../src/net/murat/ebook/R.java
echo "rm -rf ../obj/net"
rm -rf ../obj/net

# ------------------------------------------------------------------------------
# STEP 3: BACKUP ORIGINAL SOURCE FILES
# ------------------------------------------------------------------------------
log_info "Backing up original source files..."
java -cp cls: copy -v ../src/net/murat/ebook/EBook.java origFolder/src/net/murat/ebook/EBook.java
java -cp cls: copy -v ../src/net/murat/ebook/ScenePanel.java origFolder/src/net/murat/ebook/ScenePanel.java
java -cp cls: copy -v ../src/net/murat/ebook/Adding.java origFolder/src/net/murat/ebook/Adding.java
check_error "Core File Structural Backups"

# ------------------------------------------------------------------------------
# STEP 4: TMDK CONTENT GENERATION
# ------------------------------------------------------------------------------
log_info "Executing ToMDK binary layout translation engine..."
java -cp cls: ToMDK test.txt SansSerif,0,48 UTF-8 8 1300F no sil
check_error "ToMDK Serialization Layout Compiler"

# ------------------------------------------------------------------------------
# STEP 5: ASSET PROVISIONING
# ------------------------------------------------------------------------------
log_info "Preparing book content assets..."
java -cp cls: del -s ../assets/texts/*

java -cp cls: copy -v infos/r00000.dat ../assets/texts/r00000.dat
java -cp cls: copy -v UTFCustomInfo.dat ../assets/texts/info.txt
check_error "Content Payload Assets Deployment"

log_info "Updating application name..."

# ------------------------------------------------------------------------------
# STEP 6: PACKAGE NAMESPACE TRANSFORMATION
# ------------------------------------------------------------------------------
log_info "Initiating dynamic package namespace transformation..."
java -cp cls: DesignPackage sil
java -cp cls: mkdir ../src/net/murat/sil
java -cp cls: mkdir ../src/net/murat/sil/ebook
java -cp cls: move -v ../src/net/murat/ebook ../src/net/murat/sil/ebook
java -cp cls: del -s ../src/net/murat/ebook
java -cp cls:guijtracer.jar LogoGen sil
java -cp cls: ImageUtils logo_render.png 1 1 510 510
check_error "Namespace Architecture Transformation"

log_info "Removing stale compilation artifacts..."
java -cp cls: del -s ../*.keystore* ../classes.dex ../bin/*.signed.* ../bin/*.unsigned.* ../bin/*.idsig ../bin/*.apk ../obj/* ../src/net/murat/sil/ebook/R.java
java -cp cls: del -s ../obj/net

log_info "Changing working directory to project root..."
cd ..

# ------------------------------------------------------------------------------
# STEP 7: KEYSTORE GENERATION
# ------------------------------------------------------------------------------
log_info "Creating application signing keystore..."
keytool -genkey -alias EBook.keystore -keyalg RSA -keysize 3072 -validity 100000 -dname "CN=Murat inan, OU=Freelance, O=Traductor, S=Sivas, C=TR" -keystore EBook.keystore -storepass 5EmrE432 -keypass 5EmrE432
check_error "Cryptographic Keystore Provisioning"

# ------------------------------------------------------------------------------
# STEP 8: AAPT RESOURCE PROCESSING
# ------------------------------------------------------------------------------
log_info "Generating R.java using AAPT 36.0.0..."
"$AAPT" package -v -f -m \
    -S "res" \
    -J "src" \
    -M "AndroidManifest.xml" \
    -I "$ANDROID_JAR"
check_error "AAPT Resource Architecture Linker"

log_success "R.java generated."

# ------------------------------------------------------------------------------
# STEP 9: JAVA SOURCE COMPILATION
# ------------------------------------------------------------------------------
log_info "Compiling Java sources using OpenJDK 21 / Java 8 compatibility..."
javac \
    -source 1.8 \
    -target 1.8 \
    -bootclasspath "$ANDROID_JAR" \
    -sourcepath "src" \
    -cp "$ANDROID_JAR:obj" \
    -g:none \
    -proc:none \
    -nowarn \
    -O \
    -Xmaxwarns 1 \
    -d "obj" \
    "src/net/murat/sil/ebook/EBook.java"
check_error "Java Source Compilation"

log_success "Java compilation completed."

# ------------------------------------------------------------------------------
# STEP 10: D8 BYTECODE TO DEX
# ------------------------------------------------------------------------------
log_info "Converting Java bytecode to DEX using D8 36.0.0..."

rm -rf bin/d8-output
mkdir -p bin/d8-output

java \
    -cp "$D8_JAR" \
    com.android.tools.r8.D8 \
    --min-api 29 \
    --release \
    --output bin/d8-output \
    $(find obj -type f -name '*.class')
check_error "D8 Bytecode Conversion"

if [ ! -f bin/d8-output/classes.dex ]; then
    echo -e "${RED}[ERROR] D8 did not create classes.dex.${NC}"
    exit 1
fi

mv bin/d8-output/classes.dex bin/classes.dex
rm -rf bin/d8-output

log_success "classes.dex generated by D8."

# ------------------------------------------------------------------------------
# STEP 11: CREATE UNSIGNED APK
# ------------------------------------------------------------------------------
log_info "Creating unsigned APK using AAPT 36.0.0..."

"$AAPT" package -v -f \
    -M "AndroidManifest.xml" \
    -A "assets" \
    -S "res" \
    -I "$ANDROID_JAR" \
    -F "bin/EBook.unsigned.apk" \
    "bin"
check_error "Unsigned APK Packaging"

log_success "Unsigned APK created."

# ------------------------------------------------------------------------------
# STEP 12: ZIPALIGN
# ------------------------------------------------------------------------------
log_info "Aligning APK using zipalign 36.0.0..."

"$ZIPALIGN" \
    -v \
    -f \
    4 \
    "bin/EBook.unsigned.apk" \
    "bin/EBook.apk"
check_error "APK Zip Alignment"

log_success "APK alignment completed."

# ------------------------------------------------------------------------------
# STEP 13: APK SIGNING
# ------------------------------------------------------------------------------
log_info "Signing APK using apksigner 36.0.0..."

"$APKSIGNER" sign \
    --ks "EBook.keystore" \
    --ks-pass pass:5EmrE432 \
    --key-pass pass:5EmrE432 \
    --v1-signing-enabled false \
    --v2-signing-enabled true \
    --v3-signing-enabled true \
    --v4-signing-enabled false \
    "bin/EBook.apk"
check_error "APK Cryptographic Signing"

log_success "APK signed."

# ------------------------------------------------------------------------------
# STEP 14: APK SIGNATURE VERIFICATION
# ------------------------------------------------------------------------------
log_info "Verifying APK signature..."

"$APKSIGNER" verify \
    --verbose \
    "bin/EBook.apk"
check_error "APK Signature Verification"

log_success "APK signature verified."

# ------------------------------------------------------------------------------
# STEP 15: BUILD ARTIFACT CLEANUP
# ------------------------------------------------------------------------------
log_info "Removing temporary build artifacts..."

rm -fv *.keystore.old
rm -fv bin/classes.dex
rm -fv bin/*.signed.apk
rm -fv bin/*.unsigned.apk
rm -fv bin/*.idsig
rm -fv src/net/murat/sil/ebook/R.java
echo "rm -rf obj/net"
rm -rf obj/net

# ------------------------------------------------------------------------------
# STEP 16: RESTORE ORIGINAL PROJECT STRUCTURE
# ------------------------------------------------------------------------------
log_info "Restoring original project structure..."

cd arac

java -cp cls: del -s ../*.keystore.old
java -cp cls: del -s ../obj/net
java -cp cls: del -s ../assets/texts/*.*

java -cp cls: mkdir ../src/net/murat/ebook
java -cp cls: move -v ../src/net/murat/sil/ebook ../src/net/murat/ebook
java -cp cls: del -s ../src/net/murat/sil/ebook
java -cp cls: del -s ../src/net/murat/sil
java -cp cls: ReDesignPackage sil

java -cp cls: copy -v origFolder/src/net/murat/ebook/Adding.java ../src/net/murat/ebook/Adding.java
java -cp cls: CompareFiles

# ------------------------------------------------------------------------------
# STEP 17: FINAL APK NAMING
# ------------------------------------------------------------------------------
log_info "Assigning final book-specific APK filename..."

java -cp cls: del -s ../bin/*signed*.apk
java -cp cls: del -s ../bin/classes.dex

java -cp cls: move -v ../bin/EBook.apk ../bin/EBook-sil.apk

# ------------------------------------------------------------------------------
# BUILD COMPLETE
# ------------------------------------------------------------------------------
log_success "Compilation and packaging lifecycle finished successfully!"

echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN}[SUCCESS] Android API 36 book APK generated.${NC}"
echo -e "${GREEN}============================================================${NC}"

java -cp cls: dir ../bin
