# SNIPPET DEFINITIONS
# Structure: Category.Name=Content

Java.Main_Method=public static void main(String[] args) {\n\t\n}\n
Java.Print_Statement=System.out.println("");\n

C.Hello_World=#include <stdio.h>\n\nint main() {\n\tprintf("Hello!\\n");\n\treturn 0;\n}\n

HTML.Skeleton=<!DOCTYPE html>\n<html>\n<body>\n\n</body>\n</html>\n

General.Signature=Best Regards,\n[Your Name]\n

