import java.io.*;

/**
 * ============================================================================
 * LinGenerateSH
 *
 * Generates the Linux automatic Android build script "linauto.sh"
 * for the Minimalist eBook Engine.
 *
 * Build environment generated by this class:
 *
 *   OpenJDK 21
 *   Java source/target compatibility: 1.8
 *   Android Platform API 36
 *   Android Build Tools 36.0.0
 *   D8 36.0.0
 *   AAPT 36.0.0
 *   ZIPALIGN 36.0.0
 *   APKSIGNER 36.0.0
 *
 * Android configuration:
 *
 *   Minimum SDK : API 29
 *   Target SDK  : API 36
 *
 * APK signing:
 *
 *   V1 : disabled
 *   V2 : enabled
 *   V3 : enabled
 *   V4 : disabled
 *
 * ============================================================================
 */
final
public class LinGenerateSH
extends Object
implements Serializable
{

  // --------------------------------------------------------------------------
  // Input configuration defaults
  // --------------------------------------------------------------------------

  private static String FNAME="test.txt";
  private static String CHARCODE="ISO-8859-9";
  private static String LCNT="5";
  private static String HCNT="642F";
  private static String FONTSTR="SansSerif,0,27";
  private static String ALIGN="no";
  private static String ORIENTATION="landscape";


  // --------------------------------------------------------------------------
  // Private constructor
  // --------------------------------------------------------------------------

  private LinGenerateSH ()
  {
    super ();
  }


  // --------------------------------------------------------------------------
  // String representation
  // --------------------------------------------------------------------------

  public String toString ()
  {
    return "";
  }


  // --------------------------------------------------------------------------
  // Read generation configuration
  // --------------------------------------------------------------------------

  final
  private static void init (String infoname)
  throws IOException
  {
    Reader fr=new FileReader (new File (infoname));
    BufferedReader br=new BufferedReader (fr);

    String line=br.readLine (); // 1
    line=(line.split (";")[0]).trim ();
    FNAME=line;

    line=br.readLine (); // 2
    line=(line.split (";")[0]).trim ();
    CHARCODE=line;

    line=br.readLine (); // 3
    line=(line.split (";")[0]).trim ();
    LCNT=line;

    line=br.readLine (); // 4
    line=(line.split (";")[0]).trim ();
    HCNT=line;

    line=br.readLine (); // 5
    line=(line.split (";")[0]).trim ();
    FONTSTR=line;

    line=br.readLine (); // 6
    line=(line.split (";")[0]).trim ();
    ALIGN=line;

    line=br.readLine (); // 7
    line=(line.split (";")[0]).trim ();
    ORIENTATION=line;

    br.close ();
    fr.close ();

    return;
  }


  // --------------------------------------------------------------------------
  // Generate linauto.sh
  // --------------------------------------------------------------------------

  final
  private static void generate (String infoDatName)
  throws IOException, NumberFormatException
  {
    OutputStream fos=new FileOutputStream (new File ("linauto.sh"));
    PrintStream ps=new PrintStream (fos, true);


    // =========================================================================
    // SCRIPT HEADER
    // =========================================================================

    ps.println ("#!/bin/bash");
    ps.println ("");
    ps.println ("# ==============================================================================");
    ps.println ("# AUTOMATICALLY GENERATED ANDROID CLI BUILD PIPELINE");
    ps.println ("# Generated by LinGenerateSH");
    ps.println ("# Project: Minimalist eBook Engine");
    ps.println ("# Android Platform: API 36");
    ps.println ("# Build Tools: 36.0.0");
    ps.println ("# Minimum SDK: 29");
    ps.println ("# Target SDK: 36");
    ps.println ("# Java compatibility: 1.8");
    ps.println ("# Runtime compiler: OpenJDK 21");
    ps.println ("# DEX compiler: D8 36.0.0");
    ps.println ("# APK signing: APK Signature Scheme V2 + V3");
    ps.println ("# ==============================================================================");
    ps.println ("");
    
    
    // =========================================================================
    // ANSI TERMINAL COLORS
    // =========================================================================

    ps.println ("RED='\\033[0;31m'");
    ps.println ("GREEN='\\033[0;32m'");
    ps.println ("YELLOW='\\033[0;33m'");
    ps.println ("BLUE='\\033[0;34m'");
    ps.println ("NC='\\033[0m'");
    ps.println ("");


    // =========================================================================
    // ANDROID / JAVA ENVIRONMENT
    // =========================================================================

    ps.println ("export ANDROID_HOME=/usr/java/android");
    ps.println ("export JAVA_HOME=/usr/java/jdk-21.0.2");
    ps.println ("");
    ps.println ("export BUILD_TOOLS=$ANDROID_HOME/build-tools/36.0.0");
    ps.println ("export ANDROID_JAR=$ANDROID_HOME/platforms/android-36/android.jar");
    ps.println ("export D8_JAR=$BUILD_TOOLS/lib/d8.jar");
    ps.println ("");
    ps.println ("export AAPT=$BUILD_TOOLS/aapt");
    ps.println ("export ZIPALIGN=$BUILD_TOOLS/zipalign");
    ps.println ("export APKSIGNER=$BUILD_TOOLS/apksigner");
    ps.println ("");
    ps.println ("export PATH=$JAVA_HOME/bin:$BUILD_TOOLS:$ANDROID_HOME/platform-tools:$PATH");
    ps.println ("");


    // =========================================================================
    // LOGGING FUNCTIONS
    // =========================================================================

    ps.println ("log_info() {");
    ps.println ("    echo -e \"${BLUE}[INFO]${NC} $1\"");
    ps.println ("}");
    ps.println ("");

    ps.println ("log_warn() {");
    ps.println ("    echo -e \"${YELLOW}[WARN]${NC} $1\"");
    ps.println ("}");
    ps.println ("");

    ps.println ("log_success() {");
    ps.println ("    echo -e \"${GREEN}[SUCCESS]${NC} $1\"");
    ps.println ("}");
    ps.println ("");


    // =========================================================================
    // ERROR HANDLING
    // =========================================================================

    ps.println ("check_error() {");
    ps.println ("    if [ $? -ne 0 ]; then");
    ps.println ("        echo -e \"${RED}[ERROR] Critical failure encountered during: $1${NC}\"");
    ps.println ("        exit 1");
    ps.println ("    fi");
    ps.println ("}");
    ps.println ("");


    // =========================================================================
    // STEP 1
    // ENVIRONMENT CHECK
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 1: ENVIRONMENT CHECK");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Checking Java and Android build environment...\"");
    ps.println ("");
    ps.println ("java -version");
    ps.println ("");

    ps.println ("if [ ! -f \"$ANDROID_JAR\" ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] android-36/android.jar not found:${NC}\"");
    ps.println ("    echo \"$ANDROID_JAR\"");
    ps.println ("    exit 1");
    ps.println ("fi");
    ps.println ("");

    ps.println ("if [ ! -f \"$D8_JAR\" ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] D8 JAR not found:${NC}\"");
    ps.println ("    echo \"$D8_JAR\"");
    ps.println ("    exit 1");
    ps.println ("fi");
    ps.println ("");

    ps.println ("if [ ! -x \"$AAPT\" ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] AAPT 36.0.0 not found:${NC}\"");
    ps.println ("    echo \"$AAPT\"");
    ps.println ("    exit 1");
    ps.println ("fi");
    ps.println ("");

    ps.println ("if [ ! -x \"$ZIPALIGN\" ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] ZIPALIGN 36.0.0 not found:${NC}\"");
    ps.println ("    echo \"$ZIPALIGN\"");
    ps.println ("    exit 1");
    ps.println ("fi");
    ps.println ("");

    ps.println ("if [ ! -x \"$APKSIGNER\" ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] APKSIGNER 36.0.0 not found:${NC}\"");
    ps.println ("    echo \"$APKSIGNER\"");
    ps.println ("    exit 1");
    ps.println ("fi");
    ps.println ("");

    ps.println ("log_success \"Android API 36 build environment found.\"");
    ps.println ("");


    // =========================================================================
    // STEP 2
    // INITIAL CLEANUP
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 2: INITIAL CLEANUP");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Removing previous generated APK and build artifacts...\"");
    ps.println ("");

    ps.println ("rm -fv ../*.keystore.old");
    ps.println ("rm -fv ../classes.dex");
    ps.println ("rm -fv ../bin/*.apk");
    ps.println ("rm -fv ../bin/*.idsig");
    ps.println ("rm -fv ../bin/*.signed.*");
    ps.println ("rm -fv ../bin/*.unsigned.*");
    ps.println ("rm -fv ../src/net/murat/ebook/R.java");
    ps.println ("echo \"rm -rf ../obj/net\"");
    ps.println ("rm -rf ../obj/net");
    ps.println ("");


    // =========================================================================
    // STEP 3
    // BACKUP ORIGINAL SOURCE FILES
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 3: BACKUP ORIGINAL SOURCE FILES");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Backing up original source files...\"");

    ps.println ("java -cp cls: copy -v ../src/net/murat/ebook/EBook.java origFolder/src/net/murat/ebook/EBook.java");
    ps.println ("java -cp cls: copy -v ../src/net/murat/ebook/ScenePanel.java origFolder/src/net/murat/ebook/ScenePanel.java");
    ps.println ("java -cp cls: copy -v ../src/net/murat/ebook/Adding.java origFolder/src/net/murat/ebook/Adding.java");

    ps.println ("check_error \"Core File Structural Backups\"");
    ps.println ("");


    // =========================================================================
    // READ PACKAGE NAME FROM USER
    // =========================================================================

    BufferedReader inr=
      new BufferedReader (
        new InputStreamReader (System.in)
      );

    System.out.print ("Enter new package name: ");

    String pn=(inr.readLine ()).trim ();

    pn=pn.toLowerCase ();

    
    // =========================================================================
    // STEP 4
    // TMDK CONTENT GENERATION
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 4: TMDK CONTENT GENERATION");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Executing ToMDK binary layout translation engine...\"");

    ps.println (
      "java -cp cls: ToMDK "+
      FNAME+" "+
      FONTSTR+" "+
      CHARCODE+" "+
      LCNT+" "+
      HCNT+" "+
      ALIGN+" "+
      pn
    );

    ps.println ("check_error \"ToMDK Serialization Layout Compiler\"");
    ps.println ("");


    // =========================================================================
    // MANIFEST ORIENTATION
    // =========================================================================

    if (ORIENTATION.equals ("landscape"))
    {
      changeManifest (
        "../AndroidManifest.xml",
        "portrait",
        "landscape"
      );
    }
    else
    {
      changeManifest (
        "../AndroidManifest.xml",
        "landscape",
        "portrait"
      );
    }


    // =========================================================================
    // STEP 5
    // ASSET PROVISIONING
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 5: ASSET PROVISIONING");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Preparing book content assets...\"");

    ps.println ("java -cp cls: del -s ../assets/texts/*");

    ps.println ("");

    ps.println ("java -cp cls: copy -v infos/r00000.dat ../assets/texts/r00000.dat");
    ps.println ("java -cp cls: copy -v "+infoDatName+" ../assets/texts/info.txt");

    ps.println ("check_error \"Content Payload Assets Deployment\"");
    ps.println ("");


    // =========================================================================
    // APPLICATION NAME
    // =========================================================================

    ps.println ("log_info \"Updating application name...\"");

    changeProgramName (
      "../res/values/strings.xml",
      pn
    );

    ps.println ("");


    // =========================================================================
    // STEP 6
    // PACKAGE NAMESPACE TRANSFORMATION
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 6: PACKAGE NAMESPACE TRANSFORMATION");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Initiating dynamic package namespace transformation...\"");

    ps.println ("java -cp cls: DesignPackage "+pn+"");

    ps.println ("java -cp cls: mkdir ../src/net/murat/"+pn+"");

    ps.println ("java -cp cls: mkdir ../src/net/murat/"+pn+"/ebook");

    ps.println ("java -cp cls: move -v ../src/net/murat/ebook ../src/net/murat/"+pn+"/ebook");

    ps.println ("java -cp cls: del -s ../src/net/murat/ebook");

    ps.println ("java -cp cls:guijtracer.jar LogoGen "+pn+"");

    ps.println ("java -cp cls: ImageUtils logo_render.png 1 1 510 510");

    ps.println ("check_error \"Namespace Architecture Transformation\"");
    ps.println ("");


    // =========================================================================
    // PRE-COMPILATION CLEANUP
    // =========================================================================

    ps.println ("log_info \"Removing stale compilation artifacts...\"");

    ps.println (
      "java -cp cls: del -s ../*.keystore* "+
      "../classes.dex "+
      "../bin/*.signed.* "+
      "../bin/*.unsigned.* "+
      "../bin/*.idsig "+
      "../bin/*.apk "+
      "../obj/* "+
      "../src/net/murat/"+pn+"/ebook/R.java"
    );

    ps.println ("java -cp cls: del -s ../obj/net");
    ps.println ("");


    // =========================================================================
    // CHANGE WORKING DIRECTORY TO PROJECT ROOT
    // =========================================================================

    ps.println ("log_info \"Changing working directory to project root...\"");
    ps.println ("cd ..");
    ps.println ("");


    // =========================================================================
    // STEP 7
    // KEYSTORE GENERATION
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 7: KEYSTORE GENERATION");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Creating application signing keystore...\"");

    ps.println (
      "keytool -genkey "+
      "-alias EBook.keystore "+
      "-keyalg RSA "+
      "-keysize 3072 "+
      "-validity 100000 "+
      "-dname \"CN=Murat inan, OU=Freelance, O=Traductor, S=Sivas, C=TR\" "+
      "-keystore EBook.keystore "+
      "-storepass 5EmrE432 "+
      "-keypass 5EmrE432"
    );

    ps.println ("check_error \"Cryptographic Keystore Provisioning\"");
    ps.println ("");


    // =========================================================================
    // STEP 8
    // AAPT RESOURCE PROCESSING
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 8: AAPT RESOURCE PROCESSING");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Generating R.java using AAPT 36.0.0...\"");

    ps.println ("\"$AAPT\" package -v -f -m \\");
    ps.println ("    -S \"res\" \\");
    ps.println ("    -J \"src\" \\");
    ps.println ("    -M \"AndroidManifest.xml\" \\");
    ps.println ("    -I \"$ANDROID_JAR\"");

    ps.println ("check_error \"AAPT Resource Architecture Linker\"");
    ps.println ("");

    ps.println ("log_success \"R.java generated.\"");
    ps.println ("");


    // =========================================================================
    // STEP 9
    // JAVAC SOURCE COMPILATION
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 9: JAVA SOURCE COMPILATION");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Compiling Java sources using OpenJDK 21 / Java 8 compatibility...\"");

    ps.println ("javac \\");
    ps.println ("    -source 1.8 \\");
    ps.println ("    -target 1.8 \\");
    ps.println ("    -bootclasspath \"$ANDROID_JAR\" \\");
    ps.println ("    -sourcepath \"src\" \\");
    ps.println ("    -cp \"$ANDROID_JAR:obj\" \\");
    ps.println ("    -g:none \\");
    ps.println ("    -proc:none \\");
    ps.println ("    -nowarn \\");
    ps.println ("    -O \\");
    ps.println ("    -Xmaxwarns 1 \\");
    ps.println ("    -d \"obj\" \\");
    ps.println ("    \"src/net/murat/"+pn+"/ebook/EBook.java\"");

    ps.println ("check_error \"Java Source Compilation\"");
    ps.println ("");

    ps.println ("log_success \"Java compilation completed.\"");
    ps.println ("");


    // =========================================================================
    // STEP 10
    // D8 BYTECODE -> DEX
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 10: D8 BYTECODE TO DEX");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Converting Java bytecode to DEX using D8 36.0.0...\"");
    ps.println ("");

    ps.println ("rm -rf bin/d8-output");
    ps.println ("mkdir -p bin/d8-output");
    ps.println ("");

    ps.println ("java \\");
    ps.println ("    -cp \"$D8_JAR\" \\");
    ps.println ("    com.android.tools.r8.D8 \\");
    ps.println ("    --min-api 29 \\");
    ps.println ("    --release \\");
    ps.println ("    --output bin/d8-output \\");
    ps.println ("    $(find obj -type f -name '*.class')");

    ps.println ("check_error \"D8 Bytecode Conversion\"");
    ps.println ("");

    ps.println ("if [ ! -f bin/d8-output/classes.dex ]; then");
    ps.println ("    echo -e \"${RED}[ERROR] D8 did not create classes.dex.${NC}\"");
    ps.println ("    exit 1");
    ps.println ("fi");

    ps.println ("");

    ps.println ("mv bin/d8-output/classes.dex bin/classes.dex");
    ps.println ("rm -rf bin/d8-output");

    ps.println ("");

    ps.println ("log_success \"classes.dex generated by D8.\"");
    ps.println ("");


    // =========================================================================
    // STEP 11
    // CREATE UNSIGNED APK
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 11: CREATE UNSIGNED APK");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Creating unsigned APK using AAPT 36.0.0...\"");
    ps.println ("");

    ps.println ("\"$AAPT\" package -v -f \\");
    ps.println ("    -M \"AndroidManifest.xml\" \\");
    ps.println ("    -A \"assets\" \\");
    ps.println ("    -S \"res\" \\");
    ps.println ("    -I \"$ANDROID_JAR\" \\");
    ps.println ("    -F \"bin/EBook.unsigned.apk\" \\");
    ps.println ("    \"bin\"");

    ps.println ("check_error \"Unsigned APK Packaging\"");
    ps.println ("");

    ps.println ("log_success \"Unsigned APK created.\"");
    ps.println ("");


    // =========================================================================
    // STEP 12
    // ZIPALIGN
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 12: ZIPALIGN");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Aligning APK using zipalign 36.0.0...\"");
    ps.println ("");

    ps.println ("\"$ZIPALIGN\" \\");
    ps.println ("    -v \\");
    ps.println ("    -f \\");
    ps.println ("    4 \\");
    ps.println ("    \"bin/EBook.unsigned.apk\" \\");
    ps.println ("    \"bin/EBook.apk\"");

    ps.println ("check_error \"APK Zip Alignment\"");
    ps.println ("");

    ps.println ("log_success \"APK alignment completed.\"");
    ps.println ("");


    // =========================================================================
    // STEP 13
    // APK SIGNING
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 13: APK SIGNING");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Signing APK using apksigner 36.0.0...\"");
    ps.println ("");

    ps.println ("\"$APKSIGNER\" sign \\");
    ps.println ("    --ks \"EBook.keystore\" \\");
    ps.println ("    --ks-pass pass:5EmrE432 \\");
    ps.println ("    --key-pass pass:5EmrE432 \\");
    ps.println ("    --v1-signing-enabled false \\");
    ps.println ("    --v2-signing-enabled true \\");
    ps.println ("    --v3-signing-enabled true \\");
    ps.println ("    --v4-signing-enabled false \\");
    ps.println ("    \"bin/EBook.apk\"");

    ps.println ("check_error \"APK Cryptographic Signing\"");
    ps.println ("");

    ps.println ("log_success \"APK signed.\"");
    ps.println ("");


    // =========================================================================
    // STEP 14
    // APK SIGNATURE VERIFICATION
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 14: APK SIGNATURE VERIFICATION");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Verifying APK signature...\"");
    ps.println ("");

    ps.println ("\"$APKSIGNER\" verify \\");
    ps.println ("    --verbose \\");
    ps.println ("    \"bin/EBook.apk\"");

    ps.println ("check_error \"APK Signature Verification\"");
    ps.println ("");

    ps.println ("log_success \"APK signature verified.\"");
    ps.println ("");


    // =========================================================================
    // STEP 15
    // BUILD ARTIFACT CLEANUP
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 15: BUILD ARTIFACT CLEANUP");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Removing temporary build artifacts...\"");
    ps.println ("");

    ps.println ("rm -fv *.keystore.old");
    ps.println ("rm -fv bin/classes.dex");
    ps.println ("rm -fv bin/*.signed.apk");
    ps.println ("rm -fv bin/*.unsigned.apk");
    ps.println ("rm -fv bin/*.idsig");
    ps.println ("rm -fv src/net/murat/"+pn+"/ebook/R.java");
    ps.println ("echo \"rm -rf obj/net\"");
    ps.println ("rm -rf obj/net");
    ps.println ("");


    // =========================================================================
    // STEP 16
    // RESTORE ORIGINAL PROJECT STRUCTURE
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 16: RESTORE ORIGINAL PROJECT STRUCTURE");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Restoring original project structure...\"");
    ps.println ("");

    ps.println ("cd arac");
    ps.println ("");

    ps.println ("java -cp cls: del -s ../*.keystore.old");
    ps.println ("java -cp cls: del -s ../obj/net");
    ps.println ("java -cp cls: del -s ../assets/texts/*.*");
    ps.println ("");

    ps.println ("java -cp cls: mkdir ../src/net/murat/ebook");

    ps.println (
      "java -cp cls: move -v ../src/net/murat/"+
      pn+
      "/ebook ../src/net/murat/ebook"
    );

    ps.println (
      "java -cp cls: del -s ../src/net/murat/"+
      pn+
      "/ebook"
    );

    ps.println (
      "java -cp cls: del -s ../src/net/murat/"+
      pn
    );

    ps.println ("java -cp cls: ReDesignPackage "+pn+"");
    ps.println ("");

    ps.println (
      "java -cp cls: copy -v "+
      "origFolder/src/net/murat/ebook/Adding.java "+
      "../src/net/murat/ebook/Adding.java"
    );

    ps.println ("java -cp cls: CompareFiles");
    ps.println ("");


    // =========================================================================
    // STEP 17
    // FINAL APK NAMING
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# STEP 17: FINAL APK NAMING");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println ("log_info \"Assigning final book-specific APK filename...\"");
    ps.println ("");

    ps.println ("java -cp cls: del -s ../bin/*signed*.apk");
    ps.println ("java -cp cls: del -s ../bin/classes.dex");
    ps.println ("");

    ps.println (
      "java -cp cls: move -v "+
      "../bin/EBook.apk "+
      "../bin/EBook-"+pn+".apk"
    );

    ps.println ("");


    // =========================================================================
    // FINAL SUCCESS MESSAGE
    // =========================================================================

    ps.println ("# ------------------------------------------------------------------------------");
    ps.println ("# BUILD COMPLETE");
    ps.println ("# ------------------------------------------------------------------------------");

    ps.println (
      "log_success \"Compilation and packaging lifecycle finished successfully!\""
    );

    ps.println ("");

    ps.println (
      "echo -e \"${GREEN}============================================================${NC}\""
    );

    ps.println (
      "echo -e \"${GREEN}[SUCCESS] Android API 36 book APK generated.${NC}\""
    );

    ps.println (
      "echo -e \"${GREEN}============================================================${NC}\""
    );

    ps.println ("");

    ps.println ("java -cp cls: dir ../bin");


    // =========================================================================
    // CLOSE OUTPUT
    // =========================================================================

    inr.close ();

    ps.flush ();
    ps.close ();

    fos.flush ();
    fos.close ();


    System.out.println ();
    System.out.println ("First: chmod ugo+x linauto.sh");
    System.out.println ("Then : ./linauto.sh");

    return;
  }


  // ==========================================================================
  // Change AndroidManifest.xml orientation
  // ==========================================================================

  final
  private static void changeManifest (
    String fileName,
    String src,
    String dst
  )
  throws IOException
  {
    StringBuffer sb=new StringBuffer ();

    BufferedReader br=
      new BufferedReader (
        new FileReader (
          new File (fileName)
        )
      );

    String line=null;

    while ( (line=br.readLine ()) != null)
    {
      if (line.indexOf (src) < 0)
      {
        sb.append (line);
        sb.append ("\n");

        continue;
      }

      line=line.replaceAll (src, dst);

      sb.append (line);
      sb.append ("\n");
    }

    br.close ();


    PrintStream ps=
      new PrintStream (
        new FileOutputStream (
          new File (fileName)
        )
      );

    ps.print (sb.toString ());

    ps.flush ();
    ps.close ();

    return;
  }


  // ==========================================================================
  // Change EBook.java orientation
  // ==========================================================================

  final
  private static void changeEBook (
    String fileName,
    boolean isPortrait
  )
  throws IOException
  {
    // true  = portrait
    // false = landscape

    StringBuffer sb=new StringBuffer ();

    BufferedReader br=
      new BufferedReader (
        new FileReader (
          new File (fileName)
        )
      );

    String line=null;

    String src="ScenePanel panel=new ScenePanel";

    while ( (line=br.readLine ()) != null)
    {
      if (line.indexOf (src) < 0)
      {
        sb.append (line);
        sb.append ("\n");

        continue;
      }

      if (isPortrait)
      {
        line="\tScenePanel panel=new ScenePanel (this, true);";
      }
      else
      {
        line="\tScenePanel panel=new ScenePanel (this, false);";
      }

      sb.append (line);
      sb.append ("\n");
    }

    br.close ();


    PrintStream ps=
      new PrintStream (
        new FileOutputStream (
          new File (fileName)
        )
      );

    ps.print (sb.toString ());

    ps.flush ();
    ps.close ();

    return;
  }


  // ==========================================================================
  // Change Values.java maximum page count
  // ==========================================================================

  final
  private static void changeValues (
    String fileName,
    String pageCount
  )
  throws IOException
  {
    StringBuffer sb=new StringBuffer ();

    BufferedReader br=
      new BufferedReader (
        new FileReader (
          new File (fileName)
        )
      );

    String line=null;

    String src="final public static int MAX=";

    while ( (line=br.readLine ()) != null)
    {
      if (line.indexOf (src) < 0)
      {
        sb.append (line);
        sb.append ("\n");

        continue;
      }

      line=
        "    final public static int MAX="+
        pageCount+
        ";";

      sb.append (line);
      sb.append ("\n");
    }

    br.close ();


    PrintStream ps=
      new PrintStream (
        new FileOutputStream (
          new File (fileName)
        )
      );

    ps.print (sb.toString ());

    ps.flush ();
    ps.close ();

    return;
  }


  // ==========================================================================
  // Change info.dat total page count
  // ==========================================================================

  final
  private static void changeInfos (
    String fileName,
    String snum
  )
  throws IOException
  {
    StringBuffer sb=new StringBuffer ();

    BufferedReader br=
      new BufferedReader (
        new FileReader (
          new File (fileName)
        )
      );

    String line=null;

    String src="Total Page Count";

    while ( (line=br.readLine ()) != null)
    {
      if (line.indexOf (src) < 0)
      {
        sb.append (line);
        sb.append ("\n");

        continue;
      }

      line=
        snum+
        "; Total Page Count (mdk/r*.txt files count)";

      sb.append (line);
      sb.append ("\n");
    }

    br.close ();


    PrintStream ps=
      new PrintStream (
        new FileOutputStream (
          new File (fileName)
        )
      );

    ps.print (sb.toString ());

    ps.flush ();
    ps.close ();

    return;
  }


  // ==========================================================================
  // Change Android application name
  // ==========================================================================

  final
  private static void changeProgramName (
    String fileName,
    String appName
  )
  throws IOException
  {
    PrintStream ps=
      new PrintStream (
        new FileOutputStream (
          new File (fileName)
        )
      );

    ps.println ("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
    ps.println ("<resources>");
    ps.println (
      "    <string name=\"program_name\">"+
      (appName.toUpperCase (java.util.Locale.ENGLISH))+
      "</string>"
    );
    ps.println ("</resources>");

    ps.flush ();
    ps.close ();

    return;
  }


  // ==========================================================================
  // Read total page count
  // ==========================================================================

  final
  private static String getTotalPagesCount ()
  {
    String PAG="1";

    try
    {
      File fx=new File ("cnt.txt");

      Reader frx=new FileReader (fx);

      BufferedReader br=
        new BufferedReader (frx);

      String line=br.readLine ();

      PAG=line.trim ();

      br.close ();
      frx.close ();
    }
    catch (IOException ioe)
    {
      PAG="1";
    }
    catch (NumberFormatException nde)
    {
      PAG="1";
    }

    return PAG;
  }


  // ==========================================================================
  // MAIN
  // ==========================================================================

  final
  public static void main (
    final String [] args
  )
  {
    if (args.length < 1)
    {
      System.out.println (
        "Usage:\n"+
        "\tjava -cp cls: LinGenerateSH [<infoFile>]\n"
      );

      System.out.println (
        "Example:\n"+
        "\tjava -cp cls: LinGenerateSH customInfo.dat"
      );

      System.exit (-1);
    }


    try
    {
      init (args [0]);

      generate (args [0]);
    }
    catch (IOException ioe)
    {
      ioe.printStackTrace ();

      System.exit (-1);
    }
    catch (NumberFormatException nfe)
    {
      nfe.printStackTrace ();

      System.exit (-1);
    }

    System.exit (0);
  }

}
// ============================================================================
// End of LinGenerateSH
// ============================================================================
